<Project Sdk="Microsoft.Build.NoTargets">
    <PropertyGroup>
        <Description>Node.js shared library (libnode) for win-x64.</Description>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="." />
        <None Include="buildTransitive\**\*" Pack="true" PackagePath="buildTransitive\%(RecursiveDir)%(Filename)%(Extension)" />
        <None Include="$(LibNodeDir)win-x64\libnode.dll" Pack="true" PackagePath="runtimes\win-x64\native\" />
        <None Include="$(LibNodeDir)win-x64\libnode.lib" Pack="true" PackagePath="build\native\lib\win-x64\" />
        <None Include="$(LibNodeDir)win-x64\node-dotnet.dll" Pack="true" PackagePath="runtimes\win-x64\native\" />
    </ItemGroup>
</Project>
