<Project>
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <IncludeSymbols>false</IncludeSymbols>
        <NoWarn>$(NoWarn);NU5128</NoWarn>
        <PackageOutputPath>$(MSBuildThisFileDirectory)out\pkg\</PackageOutputPath>
        <Authors>Alethic</Authors>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/alethic/libnode-dotnet</PackageProjectUrl>
        <RepositoryUrl>https://github.com/alethic/libnode-dotnet</RepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageTags>node;nodejs;libnode;v8;embedding</PackageTags>

        <!-- Node build outputs, one directory per RID (downloaded by CI from the node jobs). -->
        <LibNodeDir>$(MSBuildThisFileDirectory)out\libnode\</LibNodeDir>
    </PropertyGroup>
</Project>
